<?php
/**
 * unit-notfound:/index.php
 *
 * @creation  2019-01-30
 * @version   1.0
 * @package   unit-notfound
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $db   IF_DATABASE */
/* @var $form IF_FORM */
?>
<style>
body.body label:after {
	content: "\A" ;
	white-space: pre ;
}

#control-panel {
	text-align: left;
}

#control-panel ,
#control-panel table,
#control-panel th,
#control-panel td {
	_border: 1px solid black;
}
</style>
<div style="margin: 0.5em;">
	| <a href="?">Admin</a>
	| <a href="?selftest=1">Selftest</a>
	|
</div>
<?php
//	...
if( $_GET['selftest'] ?? null ){
	return \OP\UNIT\NOTFOUND\Selftest::Auto();
};

//	...
if( $host    = $form->GetValue('host') ){
	$records = \OP\UNIT\NOTFOUND\Admin::GetRecordAtHost($host);
	$query   = http_build_query(array_diff_key($_GET,['uri'=>null]));
};
?>
<?php $form->Start() ?>
<div id="control-panel">
	<!-- Host -->
	<table>
		<tr>
			<th>
				<?php $form->Label('host') ?>
			</th>
			<td>
				<?php $form->Input('host') ?>
			</td>
		</tr>
	</table>

	<!-- URI -->
	<table>
		<?php foreach( ($records ?? []) as $record ): ?>
		<tr>
			<td><?= $record['count'] ?></td>
			<td>
				<a href="<?= "?{$query}&uri={$record['uri_ai']}" ?>">
					<?= $record['uri'] ?>
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php $form->Input('submit') ?>
</div>
<?php $form->Finish() ?>

<?php
if( $_GET['debug'] ?? null ){
	$form->Help();
	$form->Debug();
};
