<?php
/**
 * unit-notfound:/index.php
 *
 * @creation  2019-01-30
 * @version   1.0
 * @package   unit-notfound
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $db   IF_DATABASE */
/* @var $form IF_FORM */
$form = include(__DIR__.'/admin.form.php');

//	...
$form->Start();

//	...
$form->Label('host');
$form->Input('host');
echo '<br/>';

//	...
if( $host = $form->GetValue('host') ){
	//	...
	$hash = \OP\UNIT\NotFound::Hash($host);
	$ai   = $db->Quick(" ai <- t_host.hash = $hash ", ['limit'=>1]);

	//	...
	$config = [];
	$config['table'] = 't_notfound.uri <= t_uri.ai, t_notfound.ua <= t_ua.ai';
	$config['limit'] = 100;
	$config['order'] = 'sum desc';
	$config['group'] = 't_notfound.uri';
	$config['where'][] = "host = $ai";
	$config['field'][] = "t_notfound.ai  as ai     ";
	$config['field'][] = "t_notfound.uri as uri_ai ";
//	$config['field'][] = "t_notfound.ua  as ua_ai  ";
	$config['field'][] = "t_uri.uri      as uri    ";
//	$config['field'][] = "t_ua.ua        as ua     ";
	$config['field'][] = "sum(t_notfound.count) as sum ";

	//	...
	if( $records = $db->Select($config) ){
		//	...
		$name  = 'uri';
		$input = [];
		$input['name'] = $name;
		$input['type'] = 'radio';

		//	...
		foreach( $records as $record ){
			$option = [];
			$option['value'] = $record['uri_ai'];
			$option['label'] = $record['uri'] . " ({$record['sum']})";
			$input['option'][] = $option;
		};

		//	...
		$form->SetInput($input);
		$form->Input($name);
	};
};

//	...
$form->Input('submit');

//	...
$form->Finish();

echo '<hr/>';

D($records);

//	...
if( $_GET['debug'] ?? null ){
	$form->Help();
	$form->Debug();
};
?>
<style>
body.body label:after {
	content: "\A" ;
	white-space: pre ;
}
</style>
