<?php
/**
 * unit-notfound:/index.php
 *
 * @creation  2019-01-30
 * @version   1.0
 * @package   unit-notfound
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $form IF_FORM */
$form = include('admin.form.php');

//	...
$form->Start();

//	...
$form->Label('host');
$form->Input('host');
echo '<br/>';

//	...
$form->Input('submit');

//	...
$form->Finish();

/* @var $db   IF_DATABASE */
$db = \OP\UNIT\NotFound::_DB();

//	...
if( $host = $form->GetValue('host') ){
	//	...
	$hash = \OP\UNIT\NotFound::Hash($host);
	$ai   = $db->Quick(" ai <- t_host.hash = $hash ", ['limit'=>1]);

	//	...
	$config = [];
	$config['table'] = 't_notfound.uri <= t_uri.ai, t_notfound.ua <= t_ua.ai';
	$config['limit'] = 100;
	$config['order'] = 'count';
	$config['where'][] = "host = $ai";
	$config['field'][] = "t_notfound.ai  as ai  ";
	$config['field'][] = "t_uri.uri      as uri ";
	$config['field'][] = "t_ua.ua        as ua  ";
	$record = $db->Select($config);
	D($record);
};

return;

//	...
$form->Help();
$form->Debug();
