<?php
/**
 * app-skeleton-2018-nep:/asset/bootstrap/php/index.phtml
 *
 * @creation  2016-01-01:/asset/bootstrap/php/mbstring.php
 * @modification
 *            2018-12-13:/asset/bootstrap/php/index.phtml
 * @version   1.0
 * @package   core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	Correspond to  Eclipse undefined error.
if( false ){
	$module = null;
};
?>
<!doctype html>
<html>
	<head>
		<style>
		pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
		}
		</style>
	</head>
	<body>
		<h1>Does not install php-<?= $module ?> module.</h1>
		<p>Please install php-<?= $module ?> module.</p>
		<?php
		switch( PHP_OS ){ // PHP 7.2.0 --> PHP_OS_FAMILY
			case 'MacOS':
			case 'Darwin':
				include('index-osx.phtml');
				break;

			case 'WIN32':
			case 'WINNT':
				include('index-win.phtml');
				break;

			case 'AIX':
			case 'Linux':
			case 'SunOS':
				include('index-unix.phtml');
				break;

			default:
				exit(__FILE__.', '.__LINE__.', '.PHP_OS);
				break;
		}
		?>
	</body>
</html>
<?php
exit();
