<?php
/**
 * unit-test:/unit/database/orm.phtml
 *
 * @creation  2018-06-01
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>

<p class="<?= $found ? 'blue':'red' ?>">Found record</p>
<p class="<?= $valid ? 'blue':'red' ?>">Validate</p>
<p class="<?= $result !== false  ? 'blue':'red' ?>">Result</p>

<?php $form->Start() ?>
<table class="testcase">
	<?php foreach( ['required','number','integer','positive','ascii','multibyte','select','radio','checkbox','date','datetime'] as $name ): ?>
	<tr>
		<th><?= $form->Label($name) ?></th>
		<td><?= $form->Input($name) ?></td>
		<td><?= $form->Error($name) ?></td>
	</tr>
	<?php endforeach; ?>
	<tr>
		<td colspan=2 style="text-align: center;">
			<?php if( null !== ($result ?? null) ): ?>
			<p class="i0 <?= $result ? 'success':'error' ?>" style="margin: 0.5em;">
				<?= $result ? ($found ? 'Record was updated' : 'Record was created.'):'There is no change to save.' ?>
			</p>
			<?php endif; ?>
			<button>
				<?= $found ? 'Update':'Create' ?>
			</button>
		</td>
	</tr>
</table>
<?php $form->Finish() ?>
<?php
if(!$valid ){
	$form->Debug();
}
?>

<hr/>

<style>

table.testcase th,
table.testcase td {
	padding: 0 0.5em;
}

table.testcase td:nth-child(3) > span:nth-child(2) {
	display: none;
}

</style>
