<?php
/**
 * unit-test:/unit/database/scaffold/action.phtml
 *
 * @creation  2018-06-10
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $db \OP\UNIT\Database */
if( $db->isConnect() ){
	$form->Config(include('selector.form.php'));
	App::Template('selector.phtml', ['form'=>$form]);
}else{
	App::Template('login.phtml', ['form'=>$form]);
}
