<?php
/**
 * unit-test:/unit/database/scaffold/action.phtml
 *
 * @creation  2018-06-10
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="testcase-scaffold">
<?php
/* @var $db \OP\UNIT\Database */
if( $db->isConnect() ){
	//	...
	$form->Config(include('selector.form.php'));

	//	...
	$form->Values();

	//	Get database name list.
	$list['database'] = ['_'=>['label'=>null, 'value'=>null]];
	foreach( $db->Query($sql->Show([], $db), 'show') as $value ){
		$list['database'][$value]['label'] = $value;
		$list['database'][$value]['value'] = $value;
	}

	//	Get table name list at database name.
	$list['table'] = ['_'=>['label'=>null, 'value'=>null]];
	if( $database = $form->GetValue('database') ){
		foreach( $db->Query($sql->Show(['database'=>$database], $db), 'show') as $value ){
			$list['table'][$value]['label'] = $value;
			$list['table'][$value]['value'] = $value;
		}
	}

	//	...
	App::Template('selector.phtml', ['form'=>$form, 'db'=>$db, 'list'=>$list]);
}else{
	App::Template('login.phtml', ['form'=>$form]);
}
?>
</section>
<style>

#testcase-scaffold {
	_border: 1px solid black;
}

#testcase-scaffold div.record {
	_border: 1px solid black;
	float: left;
	margin-right:  1em;
	margin-bottom: 1em;
}

#record-area + * {
	clear: both;
}

</style>
