<?php
/**
 * unit-test:/unit/database/scaffold/select.phtml
 *
 * @creation  2018-06-11
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<?php $form->Start() ?>
<table>
	<?php foreach( ['database','table'] as $name ): ?>
	<tr>
		<th><?php $form->Label($name) ?></th>
		<td><?php $form->Input($name, $list[$name] ?? null) ?></td>
		<td><?php $form->Error($name) ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php $form->Finish() ?>
<?php
//	...
$database = $form->GetValue('database');
$table    = $form->GetValue('table');

//	...
if( $database and $table ){
	//	OK
}else{
	Html('Please select database and table');
	return;
}

/* @var $pager \OP\UNIT\Pager */
$pager  = Unit::Instance('Pager');
$config = ['database'=>$database, 'table'=>$table];
$config = $pager->Config($config, $db);

//	Display pagination at conditions.
echo '<hr/>';
$pager->Display();
echo '<hr/>';

/* @var $db \OP\UNIT\Database */
printf('<div id="record-area">');
foreach( $db->Select($config) as $record ){
	printf('<div class="record">');
	printf('<a href="?%s">Edit of this record</a>', http_build_query( array_merge($_GET, ['ai'=>$record['ai']]) ));
	Json($record, '.OP_DUMP');
	printf('</div>');
}
printf('</div><br/>');

//	Display pagination at conditions.
echo '<hr/>';
$pager->Display();
echo '<hr/>';

//	...
App::WebPack('unit:/dump/dump.js');
App::WebPack('unit:/dump/dump.css');
