<?php
/**
 * app-skeleton-2018-nep:/app/bootstrap/op/rewrite-apache.phtml
 *
 * @creation  2016-11-25
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
global $_OP;

//	Calc rewrite base directory.
$rewrite_base = substr($_OP[APP_ROOT], strlen($_SERVER['DOCUMENT_ROOT']));

?>
<h1>How to boot the onepiece-framework at the Apache web server.</h1>
<ol>
	<li>
		<p>Please open <b>"<?= rtrim(ConvertPath('app:/'),'/') ?>/.htaccess"</b> file.</p>
		<p><i><b>Attention!</b> This file is invisible attribute file.</i></p>
	</li>
	<li>
		<p>
			Look for line 38.<br/>
			Change the value of "RewriteEngine" from "Off" to "On".
		</p>
	</li>
	<?php if( $rewrite_base !== '/' ): ?>
	<li>
		<p>
			Look for line 41.<br/>
			Change the value of "RewriteBase" from "/" to "<?= $rewrite_base ?>".
		</p>
	</li>
	<?php endif; ?>
	<li>
		<p>
			Please reload this page.
		</p>
	</li>
</ol>
