<?php
/**
 * app-skeleton-2018-nep:/asset/template/404_not_found.phtml
 *
 * @creation  2017-08-29
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section>
	<h2>404 Not found</h2>
	<p>This page for could not be found.</p>
	<img src="<?= ConvertURL('app:/img/404.png') ?>"/>
</section>
