<?php
/**
 * app-skeleton-2018-nep:/asset/template/head.php
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

//	Get layout name
$layout = App::Layout();

//	Get webpack unique hash key.
if( Unit::Load('webpack') ){
	$hash_js  = \OP\UNIT\WebPack::Hash('js');
	$hash_css = \OP\UNIT\WebPack::Hash('css');
}

?>
<!-- Charset -->
<meta charset="utf-8" />
<meta http-equiv="Content-Type"  content="text/html; charset=UTF-8" />

<!-- For SmartPhone -->
<meta name="viewport"            content="width=device-width,initial-scale=1" />
<meta name="format-detection"    content="telephone=no" />

<!-- Disable content cache -->
<meta http-equiv="Pragma"        content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Expires"       content="-1" />

<!-- Icon -->
<link rel="icon"			 type="image/x-icon" href="<?= ConvertURL("app:/img/icon.png") ?>" />
<link rel="apple-touch-icon" type="image/png"	 href="<?= ConvertURL("app:/img/icon.png") ?>" />
<link rel="apple-touch-icon-precomposed"
							 type="image/png"	 href="<?= ConvertURL("app:/img/icon.png") ?>" />

<!-- JavaScript -->
<script type="text/javascript" src="<?= ConvertURL("app:/webpack/js/?layout={$layout}&hash={$hash_js}") ?>"></script>

<!-- Stylesheet -->
<link rel="stylesheet" type="text/css" href="<?= ConvertURL("app:/webpack/css/?layout={$layout}&hash={$hash_css}") ?>" />

<!-- title -->
<title><?= App::Title() ?></title>
