<?php
/**
 * app-skeleton-2018-nep:/asset/template/header.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<header>
	<a href="<?= ConvertURL('app:/') ?>">onepiece-framework</a>
	<?php
	if( Unit::Load('GDPR') ){
		OP\UNIT\GDPR::Html();
	}
	?>
</header>
