<?php
/**
 * app-skeleton-2018-nep:/asset/template/welcome.phtml
 *
 * @creation  2017-07-28
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="welcome">
	<h2>Welcome to the onepiece-framework!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations! onepiece-framework would booted!!
		How was it? Have you boot easily? Yes, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<p>
		For example, you can easily find the file of endpoint.
		Please refer to this page's URL, Directories are intact.
		We this mechanism so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>
</section>
<?php if( Env::isLocalhost() ): ?>
	<?php
	//	...
	$links = null;

	//	...
	$app_root = ConvertPath('app:/');

	//	...
	foreach( scandir($app_root) as $file ){
		//	...
		$path = $app_root . $file;

		//	...
		if( is_link($path) ){
			$link = readlink($path);
			$link = rtrim($link, '/');
			$temp = explode('/', $link);
			$file = array_pop($temp);
			$links[$file] = true;
		};
	};

	//	...
	$keys = ['test','reference','admin'];

	?>
	<?php if( count($links) !== count($keys) ): ?>
	<hr style="clear:both;" />
	<section>
		<?php
		$asset_root = (ConvertPath('app:/asset/') === ConvertPath('asset:/')) ? './asset/':ConvertPath('asset:/');
		?>
		<h2>Example</h2>
<code>
cd <?= $app_root . "\n" ?>
<?php foreach( $keys as $key ): ?>
<?php if( empty($links[$key])): ?>
ln -s <?= $asset_root.$key?> _<?= $key ?><br/>
<?php endif; ?>
<?php endforeach; ?>
</code>
	</section>
	<?php else: ?>
		<hr/>
	<?php endif; ?>
<?php else: ?>
	<hr/>
<?php endif; ?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
