<?php
/**
 * app-skeleton-2018-nep:/asset/template/welcome.phtml
 *
 * @creation  2017-07-28
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="welcome">
	<h2>Welcome to the onepiece-framework!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations! onepiece-framework would booted!!
		How was it? Have you boot easily? Yes, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<p>
		For example, you can easily find the file of endpoint.
		Please refer to this page's URL, Directories are intact.
		We this mechanism so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>
</section>

<hr/>

<?php if( Env::isLocalhost() ): ?>
<section>
	<?php
	$asset_root = (ConvertPath('app:/asset/') === ConvertPath('asset:/')) ? './asset/':ConvertPath('asset:/');
	?>
	<h2>Example</h2>
	<code>
	cd <?= ConvertPath("app:/\n") ?>
	ln -s <?= $asset_root.'test' ?> _testcase
	ln -s <?= $asset_root.'reference' ?> _reference
	</code>
</section>
<?php endif; ?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
