<?php
/**
 * unit-pager:/pager.phtml
 *
 * @creation  2018-12-19
 * @version   1.0
 * @package   unit-pager
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
if( false ){
	$total_pages  = null;
	$current_page = null;
	$option       = null;

};

//	...
$arm   = $option['wings'];
$gibbon = ($arm * 2) +1;

//	...
$st = $current_page - $arm;
$en = $current_page + $arm;

//	...
D("st=$st, en=$en, current_page=$current_page, total=$total_pages, gibbon=$gibbon, arm=$arm");

//	...
if( $st < 2 ){
	$st = 2;
	$en = $st + ($arm * 2);
	if( $en >= $total_pages ){
		$en  = $total_pages -1;
	};
};

//	...
if( $en >= $total_pages ){
	$en  = $total_pages -1;
	$st  = $en - ($arm * 2);
	if( $st < 2 ){
		$st = 2;
	};
};

//	...
D("st=$st, en=$en");
?>
<nav class="OP pager">
	<?php
	//	Forward mark.
	if( $current_page !== 1 ){
		$i = 'forward';
		include(__DIR__.'/pager-num.phtml');
	};

	//	Got to first page.
	$i = 1;
	include(__DIR__.'/pager-num.phtml');

	//	To omit mark.
	if( $st > 2 and $current_page > 2 ){
		$i = 'omit';
		include(__DIR__.'/pager-num.phtml');
	};

	//	Each pages.
	if( $total_pages > 1 ){
		for( $i=$st; $i<=$en; $i++ ){
			include(__DIR__.'/pager-num.phtml');
		};
	};

	//	To omit mark.
	if( $current_page < $en and $en < $total_pages -1 ){
		$i = 'omit';
		include(__DIR__.'/pager-num.phtml');
	};

	//	Go to last page.
	$i = $total_pages;
	include(__DIR__.'/pager-num.phtml');

	//	Backward mark.
	if( $current_page !== $total_pages ){
		$i = 'backward';
		include(__DIR__.'/pager-num.phtml');
	};
	?>
</nav>
